# Generated by Django for the Election Release Archive.
import archive.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name="Collection", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("slug", models.SlugField(unique=True)), ("code", models.CharField(max_length=8, unique=True)),
            ("title", models.CharField(max_length=240)), ("description", models.TextField(blank=True)),
            ("source_url", models.URLField(blank=True)), ("display_order", models.PositiveSmallIntegerField(default=0)),
        ], options={"ordering": ("display_order", "title")}),
        migrations.CreateModel(name="ImportRun", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("path_label", models.CharField(max_length=500)), ("started_at", models.DateTimeField(auto_now_add=True)),
            ("completed_at", models.DateTimeField(blank=True, null=True)), ("files_seen", models.PositiveIntegerField(default=0)),
            ("files_imported", models.PositiveIntegerField(default=0)), ("duplicates", models.PositiveIntegerField(default=0)),
            ("errors", models.PositiveIntegerField(default=0)), ("log", models.JSONField(blank=True, default=list)),
        ]),
        migrations.CreateModel(name="SourceFile", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("original_filename", models.CharField(max_length=500)), ("stored_file", models.FileField(max_length=700, upload_to=archive.models.original_upload_to)),
            ("sha256", models.CharField(db_index=True, max_length=64, unique=True)), ("size", models.PositiveBigIntegerField()),
            ("mime_type", models.CharField(max_length=100)), ("page_count", models.PositiveIntegerField(default=0)),
            ("pdf_metadata", models.JSONField(blank=True, default=dict)), ("imported_at", models.DateTimeField(auto_now_add=True)),
            ("source_url", models.URLField(blank=True)), ("import_status", models.CharField(choices=[("pending", "Pending"), ("complete", "Complete"), ("duplicate", "Duplicate"), ("error", "Error")], default="pending", max_length=20)),
            ("extraction_status", models.CharField(choices=[("pending", "Pending"), ("complete", "Complete"), ("duplicate", "Duplicate"), ("error", "Error")], default="pending", max_length=20)),
            ("ocr_status", models.CharField(choices=[("pending", "Pending"), ("complete", "Complete"), ("duplicate", "Duplicate"), ("error", "Error")], default="pending", max_length=20)),
            ("contains_embedded_text", models.BooleanField(default=False)), ("ocr_required", models.BooleanField(default=False)),
            ("error_details", models.TextField(blank=True)),
            ("collection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="source_files", to="archive.collection")),
            ("import_run", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_files", to="archive.importrun")),
        ], options={"ordering": ("-imported_at",)}),
        migrations.CreateModel(name="Document", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("stable_id", models.CharField(editable=False, max_length=32, unique=True)),
            ("title", models.CharField(max_length=500)), ("title_source", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], default="imported", max_length=20)),
            ("document_type", models.CharField(blank=True, max_length=160)), ("originating_agency", models.CharField(blank=True, max_length=240)),
            ("agency_source", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], default="inferred", max_length=20)),
            ("document_date", models.DateField(blank=True, null=True)), ("date_precision", models.CharField(choices=[("day", "Day"), ("month", "Month"), ("year", "Year"), ("unknown", "Unknown")], default="unknown", max_length=10)),
            ("date_source", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], default="inferred", max_length=20)),
            ("case_number", models.CharField(blank=True, max_length=160)), ("printed_identifiers", models.JSONField(blank=True, default=list)),
            ("classification_markings", models.JSONField(blank=True, default=list)), ("declassification_markings", models.JSONField(blank=True, default=list)),
            ("summary", models.TextField(blank=True)), ("summary_source", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], default="editorial", max_length=20)),
            ("start_page", models.PositiveIntegerField(default=1)), ("end_page", models.PositiveIntegerField(default=1)), ("has_redactions", models.BooleanField(default=False)),
            ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("review_notes", models.TextField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True)),
            ("collection", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="archive.collection")),
            ("source_file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="archive.sourcefile")),
        ], options={"ordering": ("stable_id",)}),
        migrations.AddConstraint(model_name="document", constraint=models.CheckConstraint(condition=models.Q(("end_page__gte", models.F("start_page"))), name="valid_document_page_range")),
        migrations.CreateModel(name="Page", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("source_page_number", models.PositiveIntegerField()),
            ("logical_page_number", models.PositiveIntegerField()), ("stable_page_id", models.CharField(editable=False, max_length=48, unique=True)),
            ("extracted_text", models.TextField(blank=True)), ("ocr_text", models.TextField(blank=True)), ("preferred_searchable_text", models.TextField(blank=True)),
            ("page_image", models.FileField(blank=True, max_length=700, upload_to="derived/page-images/")), ("printed_page_label", models.CharField(blank=True, max_length=80)),
            ("extraction_method", models.CharField(choices=[("embedded", "Embedded text"), ("ocr", "OCR"), ("none", "No text")], default="none", max_length=20)),
            ("extraction_confidence", models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ("has_redactions", models.BooleanField(default=False)), ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="archive.document")),
            ("source_file", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pages", to="archive.sourcefile")),
        ], options={"ordering": ("logical_page_number",)}),
        migrations.AddConstraint(model_name="page", constraint=models.UniqueConstraint(fields=("document", "logical_page_number"), name="unique_logical_page")),
        migrations.AddConstraint(model_name="page", constraint=models.UniqueConstraint(fields=("source_file", "source_page_number", "document"), name="unique_source_page_per_document")),
        migrations.CreateModel(name="EditorialMetadata", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("field_name", models.CharField(max_length=100)),
            ("value", models.TextField()), ("source_type", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], max_length=20)),
            ("confidence", models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ("reviewed", models.BooleanField(default=False)), ("reviewer_notes", models.TextField(blank=True)),
            ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metadata_entries", to="archive.document")),
        ], options={"verbose_name_plural": "editorial metadata"}),
        migrations.CreateModel(name="Entity", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=300)),
            ("slug", models.SlugField(unique=True)), ("entity_type", models.CharField(choices=[("person", "Person"), ("organization", "Organization"), ("government_agency", "Government agency"), ("state", "State"), ("country", "Country"), ("location", "Location"), ("company", "Company"), ("software_system", "Software system"), ("voting_system", "Voting system"), ("investigation", "Investigation"), ("other", "Other")], max_length=30)),
            ("aliases", models.JSONField(blank=True, default=list)), ("description", models.TextField(blank=True)),
            ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
        ], options={"ordering": ("name",)}),
        migrations.AddConstraint(model_name="entity", constraint=models.UniqueConstraint(fields=("name", "entity_type"), name="unique_named_entity")),
        migrations.CreateModel(name="EntityMention", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("quoted_text", models.TextField(blank=True)),
            ("character_start", models.PositiveIntegerField(blank=True, null=True)), ("character_end", models.PositiveIntegerField(blank=True, null=True)),
            ("confidence", models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ("source_type", models.CharField(choices=[("printed", "Printed in source"), ("embedded", "Embedded metadata"), ("inferred", "Inferred"), ("editorial", "Editorial"), ("imported", "Imported")], max_length=20)),
            ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entity_mentions", to="archive.document")),
            ("entity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mentions", to="archive.entity")),
            ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entity_mentions", to="archive.page")),
        ]),
        migrations.CreateModel(name="Claim", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=400)),
            ("slug", models.SlugField(unique=True)), ("normalized_claim_text", models.TextField()), ("detailed_description", models.TextField(blank=True)),
            ("claim_date", models.DateField(blank=True, null=True)), ("status", models.CharField(choices=[("allegation", "Allegation"), ("preliminary_finding", "Preliminary finding"), ("agency_assessment", "Agency assessment"), ("confirmed_fact", "Confirmed fact"), ("disputed", "Disputed"), ("contradicted", "Contradicted"), ("unresolved", "Unresolved"), ("withdrawn", "Withdrawn")], default="allegation", max_length=30)),
            ("evidence_type", models.CharField(blank=True, max_length=40)), ("evidence_strength", models.CharField(blank=True, max_length=40)),
            ("unresolved_questions", models.TextField(blank=True)), ("editorial_notes", models.TextField(blank=True)),
            ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("claimant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="claims_made", to="archive.entity")),
        ]),
        migrations.CreateModel(name="ClaimCitation", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("excerpt", models.TextField()),
            ("relationship_type", models.CharField(choices=[("supports", "Supports"), ("qualifies", "Qualifies"), ("contradicts", "Contradicts"), ("mentions", "Mentions"), ("background", "Background")], max_length=20)),
            ("editorial_explanation", models.TextField(blank=True)), ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("claim", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="citations", to="archive.claim")),
            ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claim_citations", to="archive.document")),
            ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="claim_citations", to="archive.page")),
        ]),
        migrations.CreateModel(name="DocumentRelationship", fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("relationship_type", models.CharField(choices=[("attachment", "Attachment"), ("response", "Response"), ("references", "References"), ("duplicate", "Duplicate"), ("related", "Related")], max_length=20)),
            ("explanation", models.TextField(blank=True)), ("review_state", models.CharField(choices=[("unreviewed", "Unreviewed"), ("reviewed", "Reviewed"), ("needs_attention", "Needs attention")], default="unreviewed", max_length=20)),
            ("related_document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_relationships", to="archive.document")),
            ("source_document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_relationships", to="archive.document")),
        ]),
        migrations.AddConstraint(model_name="documentrelationship", constraint=models.UniqueConstraint(fields=("source_document", "related_document", "relationship_type"), name="unique_document_relationship")),
    ]
