# Generated by Django 5.2.16 on 2026-07-18 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_seed_collections'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedactionFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('live_annotation', 'Live redaction annotation'), ('opaque_overlay', 'Opaque overlay over text'), ('hidden_text', 'Hidden text layer'), ('prior_revision', 'Earlier PDF revision'), ('embedded_content', 'Embedded content'), ('other', 'Other verified method')], max_length=30)),
                ('recovered_text', models.TextField()),
                ('public_explanation', models.TextField()),
                ('technical_basis', models.TextField(blank=True)),
                ('coordinates', models.JSONField(blank=True, default=list)),
                ('review_state', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('needs_attention', 'Needs attention')], default='unreviewed', max_length=20)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redaction_findings', to='archive.page')),
            ],
            options={
                'ordering': ('page__document__stable_id', 'page__logical_page_number', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('published', False), ('review_state', 'reviewed'), _connector='OR'), name='published_redaction_finding_is_reviewed')],
            },
        ),
    ]
